name: Development container
on:
    workflow_dispatch:

jobs:
    build_backend:
        name: 🏗 Build and Push Backend Dev Image
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 50

        - name: Cache Build Artifacts
          uses: actions/cache@v4
          id: cache
          with:
            path: ./build-cache
            key: backend-build-${{ github.sha }}
            restore-keys: backend-build-

        - name: Build Backend Image
          run: make build container=backend

        - name: Login to GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Tag Image as `latest`
          run: docker tag openfoodfacts-server/backend:dev ghcr.io/jagjeevanak/backend:latest

        - name: Push Image
          run: docker push ghcr.io/jagjeevanak/backend:latest
